GET http://localhost:8080/api/order

### Menu

GET http://localhost:8060/api/menu

### Order to Kitchen

GET http://localhost:8060/api/order-to-kitchen

### Actuator Endpoints

http://localhost:8060/actuator

### Actuator Prometheus Registry

http://localhost:8060/actuator/prometheus

### Actuator Info

http://localhost:8060/actuator/info

### Actuator health

http://localhost:8060/actuator/health

### Actuator health liveness

http://localhost:8060/actuator/health/liveness

### Actuator health readiness

http://localhost:8060/actuator/health/readiness