receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
     timeout: 1s
     send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed 

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp:
    endpoint: "tempo:4317"

  zipkin:
    endpoint: "http://jaeger-all-in-one:9411/api/v2/spans"
    sending_queue:
      enabled: true
      queue_size: 5000  # Erhöhe die Warteschlange

extensions:
  health_check:
    endpoint: 0.0.0.0:13133  
  pprof:
    endpoint: 0.0.0.0:1888   
  zpages:
    endpoint: 0.0.0.0:55679  

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
