server:
  port: 8060

spring:
  application:
    name: order
  security:
    oauth2:
      resourceserver:
        issuer-uri: http://${KEYCLOAK_HOST:keycloak}:8080/realms/freddy
management:
  info:
    git:
      mode: simple
      enabled: true
    java:
      enabled: true
  otlp:
    metrics:
      export:
        url: http://${OTEL_HOST:localhost}:4318/v1/metrics
        batch-size: 1
        step: 10s
    tracing:
      endpoint: http://${OTEL_HOST:localhost}:4318/v1/traces
  tracing:
    sampling:
      probability: 1
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
#  metrics:
#    tags:
#      service: kitchen

kitchen-service:
  url: http://localhost:8070

delivery-service:
  url: http://localhost:8060

# logging:
#  config: classpath:logback.xml